version: '2.1'
services:

  consul:
    image: wcshub.azurecr.io/ip2c.consul:latest
    ports:
      - "8500:8500"

  webapi:
    image: wcshub.azurecr.io/ip2c.webapi.selfhost:latest
    environment:
      - CONSUL_URL="http://consul:8500"
      - NETWORK="0.0.0.0/0"
    depends_on:
      - consul

  console:
    image: wcshub.azurecr.io/ip2c.console:latest
    environment:
      - CONSUL_URL="http://consul:8500"
    depends_on:
      - consul
      - webapi

networks:
  default:
    external:
      name: nat
