version: '2.1'
services:
  webapi:
    image: ip2c/webapi
    volumes:
      - ipinfo_data:c:/inetpub/wwwroot/app_data
      
  worker:
    image: ip2c/worker
    volumes:
      - ipinfo_data:c:/IP2C.Worker/data

  proxy:
    build: ./IP2C.ReverseProxy
    ports:
      - 80:80
    networks:
      default:
        ipv4_address: 172.24.225.100

volumes:
  ipinfo_data:
#  ipinfo_logs:

networks:
  default:
    external:
      name: nat
